import { InjectionKey } from "vue";
import { createStore, useStore as baseUseStore, Store } from "vuex";
import { Category } from "../types";

export const key: InjectionKey<Store<State>> = Symbol();

export interface State {
  [key: string]: string | number | any;
}

export const store = createStore<State>({
  state: {
    userAvatar: "aaaaaaaaaaaa",
    isDarkMode: false,
    maleCategoriesHd: [
      {
        name: "shapes",
        options: [
          "azzzzzzzzzzz",
          "bzzzzzzzzzzz",
          "czzzzzzzzzzz",
          "dzzzzzzzzzzz",
          "ezzzzzzzzzzz",
          "fzzzzzzzzzzz",
          "gzzzzzzzzzzz",
        ],
        index: 0,
      },
      {
        name: "eyes",
        options: [
          "aazzzzzzzzzz",
          "abzzzzzzzzzz",
          "aczzzzzzzzzz",
          "adzzzzzzzzzz",
          "aezzzzzzzzzz",
          "afzzzzzzzzzz",
          "agzzzzzzzzzz",
          "ahzzzzzzzzzz",
          "aizzzzzzzzzz",
          "ajzzzzzzzzzz",
          "akzzzzzzzzzz",
          "alzzzzzzzzzz",
          "amzzzzzzzzzz",
          "anzzzzzzzzzz",
          "aozzzzzzzzzz",
          "apzzzzzzzzzz",
          "aqzzzzzzzzzz",
          "arzzzzzzzzzz",
          "aszzzzzzzzzz",
          "atzzzzzzzzzz",
          "auzzzzzzzzzz",
          "avzzzzzzzzzz",
          "awzzzzzzzzzz",
          "axzzzzzzzzzz",
        ],
        index: 1,
      },
      {
        name: "brows",
        options: [
          "azazzzzzzzzz",
          "azbzzzzzzzzz",
          "azczzzzzzzzz",
          "azdzzzzzzzzz",
          "azezzzzzzzzz",
          "azfzzzzzzzzz",
          "azgzzzzzzzzz",
          "azhzzzzzzzzz",
          "azizzzzzzzzz",
          "azjzzzzzzzzz",
          "azkzzzzzzzzz",
          "azlzzzzzzzzz",
          "azmzzzzzzzzz",
          "aznzzzzzzzzz",
          "azozzzzzzzzz",
          "azpzzzzzzzzz",
          "azqzzzzzzzzz",
          "azrzzzzzzzzz",
          "azszzzzzzzzz",
          "aztzzzzzzzzz",
          "azuzzzzzzzzz",
        ],
        index: 2,
      },
      {
        name: "mouths",
        options: [
          "azzazzzzzzzz",
          "azzbzzzzzzzz",
          "azzczzzzzzzz",
          "azzdzzzzzzzz",
          "azzezzzzzzzz",
          "azzfzzzzzzzz",
          "azzgzzzzzzzz",
          "azzhzzzzzzzz",
          "azzizzzzzzzz",
          "azzjzzzzzzzz",
          "azzkzzzzzzzz",
          "azzlzzzzzzzz",
          "azzmzzzzzzzz",
          "azznzzzzzzzz",
          "azzozzzzzzzz",
          "azzpzzzzzzzz",
          "azzqzzzzzzzz",
          "azzrzzzzzzzz",
          "azzszzzzzzzz",
          "azztzzzzzzzz",
          "azzuzzzzzzzz",
        ],
        index: 3,
      },
      {
        name: "ears",
        options: [
          "azzzazzzzzzz",
          "azzzbzzzzzzz",
          "azzzczzzzzzz",
          "azzzdzzzzzzz",
          "azzzezzzzzzz",
          "azzzfzzzzzzz",
          "azzzgzzzzzzz",
          "azzzhzzzzzzz",
        ],
        index: 4,
      },
      {
        name: "noses",
        options: [
          "azzzzazzzzzz",
          "azzzzbzzzzzz",
          "azzzzczzzzzz",
          "azzzzdzzzzzz",
          "azzzzezzzzzz",
          "azzzzfzzzzzz",
          "azzzzgzzzzzz",
          "azzzzhzzzzzz",
          "azzzzizzzzzz",
          "azzzzjzzzzzz",
          "azzzzkzzzzzz",
          "azzzzlzzzzzz",
          "azzzzmzzzzzz",
          "azzzznzzzzzz",
          "azzzzozzzzzz",
          "azzzzpzzzzzz",
          "azzzzqzzzzzz",
          "azzzzrzzzzzz",
          "azzzzszzzzzz",
          "azzzztzzzzzz",
        ],
        index: 5,
      },
      {
        name: "necks",
        options: [
          "azzzzzazzzzz",
          "azzzzzbzzzzz",
          "azzzzzczzzzz",
          "azzzzzdzzzzz",
          "azzzzzezzzzz",
          "azzzzzfzzzzz",
          "azzzzzgzzzzz",
          "azzzzzhzzzzz",
          "azzzzzizzzzz",
          "azzzzzjzzzzz",
          "azzzzzkzzzzz",
        ],
        index: 6,
      },
      {
        name: "hairs",
        options: [
          "azzzzzzazzzz",
          "azzzzzzbzzzz",
          "azzzzzzczzzz",
          "azzzzzzdzzzz",
          "azzzzzzezzzz",
          "azzzzzzfzzzz",
          "azzzzzzgzzzz",
          "azzzzzzhzzzz",
          "azzzzzzizzzz",
          "azzzzzzjzzzz",
          "azzzzzzkzzzz",
          "azzzzzzlzzzz",
          "azzzzzzmzzzz",
          "azzzzzznzzzz",
          "azzzzzzozzzz",
          "azzzzzzpzzzz",
          "azzzzzzqzzzz",
          "azzzzzzrzzzz",
        ],
        index: 7,
      },
      {
        name: "staches",
        options: [
          "azzzzzzzazzz",
          "azzzzzzzbzzz",
          "azzzzzzzczzz",
          "azzzzzzzdzzz",
          "azzzzzzzezzz",
          "azzzzzzzfzzz",
          "azzzzzzzgzzz",
          "azzzzzzzhzzz",
          "azzzzzzzizzz",
          "azzzzzzzjzzz",
          "azzzzzzzkzzz",
          "azzzzzzzlzzz",
          "azzzzzzzmzzz",
          "azzzzzzznzzz",
          "azzzzzzzozzz",
          "azzzzzzzpzzz",
          "azzzzzzzqzzz",
          "azzzzzzzrzzz",
          "azzzzzzzszzz",
        ],
        index: 8,
      },
      {
        name: "lines",
        options: [
          "azzzzzzzzazz",
          "azzzzzzzzbzz",
          "azzzzzzzzczz",
          "azzzzzzzzdzz",
          "azzzzzzzzezz",
          "azzzzzzzzfzz",
          "azzzzzzzzgzz",
          "azzzzzzzzhzz",
        ],
        index: 9,
      },
      {
        name: "props",
        options: [
          "azzzzzzzzzaz",
          "azzzzzzzzzbz",
          "azzzzzzzzzcz",
          "azzzzzzzzzdz",
          "azzzzzzzzzez",
          "azzzzzzzzzfz",
          "azzzzzzzzzgz",
          "azzzzzzzzzhz",
          "azzzzzzzzziz",
          "azzzzzzzzzjz",
          "azzzzzzzzzkz",
          "azzzzzzzzzlz",
          "azzzzzzzzzmz",
          "azzzzzzzzznz",
          "azzzzzzzzzoz",
          "azzzzzzzzzpz",
          "azzzzzzzzzqz",
          "azzzzzzzzzrz",
          "azzzzzzzzzsz",
          "azzzzzzzzztz",
        ],
        index: 10,
      },
      //   {
      //     name: "props2",
      //     options: [
      //       "azzzzzzzzzza",
      //       "azzzzzzzzzzb",
      //       "azzzzzzzzzzc",
      //       "azzzzzzzzzzd",
      //       "azzzzzzzzzze",
      //       "azzzzzzzzzzf",
      //       "azzzzzzzzzzg",
      //       "azzzzzzzzzzh",
      //       "azzzzzzzzzzi",
      //       "azzzzzzzzzzj",
      //       "azzzzzzzzzzk",
      //       "azzzzzzzzzzl",
      //       "azzzzzzzzzzm",
      //       "azzzzzzzzzzn",
      //       "azzzzzzzzzzo",
      //       "azzzzzzzzzzp",
      //       "azzzzzzzzzzq",
      //       "azzzzzzzzzzr",
      //       "azzzzzzzzzzs",
      //       "azzzzzzzzzzt",
      //       "azzzzzzzzzzu",
      //     ],
      //     index: 11,
      //   },
    ] as Category[],

    femaleCategoriesHd: [
      {
        name: "shapes",
        options: [
          "azzzzzzzzzzz",
          "bzzzzzzzzzzz",
          "czzzzzzzzzzz",
          "dzzzzzzzzzzz",
          "ezzzzzzzzzzz",
          "fzzzzzzzzzzz",
          "gzzzzzzzzzzz",
        ],
        index: 0,
      },
      {
        name: "eyes",
        options: [
          "aazzzzzzzzzz",
          "abzzzzzzzzzz",
          "aczzzzzzzzzz",
          "adzzzzzzzzzz",
          "aezzzzzzzzzz",
          "afzzzzzzzzzz",
          "agzzzzzzzzzz",
          "ahzzzzzzzzzz",
          "aizzzzzzzzzz",
          "ajzzzzzzzzzz",
          "akzzzzzzzzzz",
          "alzzzzzzzzzz",
          "amzzzzzzzzzz",
          "anzzzzzzzzzz",
          "aozzzzzzzzzz",
          "apzzzzzzzzzz",
          "aqzzzzzzzzzz",
          "arzzzzzzzzzz",
          "aszzzzzzzzzz",
          "atzzzzzzzzzz",
          "auzzzzzzzzzz",
          "avzzzzzzzzzz",
          "awzzzzzzzzzz",
          "axzzzzzzzzzz",
          "ayzzzzzzzzzz",
        ],
        index: 1,
      },
      {
        name: "brows",
        options: [
          "azazzzzzzzzz",
          "azbzzzzzzzzz",
          "azczzzzzzzzz",
          "azdzzzzzzzzz",
          "azezzzzzzzzz",
          "azfzzzzzzzzz",
          "azgzzzzzzzzz",
          "azhzzzzzzzzz",
          "azizzzzzzzzz",
          "azjzzzzzzzzz",
          "azkzzzzzzzzz",
          "azlzzzzzzzzz",
          "azmzzzzzzzzz",
          "aznzzzzzzzzz",
          "azozzzzzzzzz",
          "azpzzzzzzzzz",
          "azqzzzzzzzzz",
          "azrzzzzzzzzz",
        ],
        index: 2,
      },
      {
        name: "mouths",
        options: [
          "azzazzzzzzzz",
          "azzbzzzzzzzz",
          "azzczzzzzzzz",
          "azzdzzzzzzzz",
          "azzezzzzzzzz",
          "azzfzzzzzzzz",
          "azzgzzzzzzzz",
          "azzhzzzzzzzz",
          "azzizzzzzzzz",
          "azzjzzzzzzzz",
          "azzkzzzzzzzz",
          "azzlzzzzzzzz",
          "azzmzzzzzzzz",
          "azznzzzzzzzz",
          "azzozzzzzzzz",
          "azzpzzzzzzzz",
          "azzqzzzzzzzz",
          "azzrzzzzzzzz",
          "azzszzzzzzzz",
          "azztzzzzzzzz",
          "azzuzzzzzzzz",
          "azzvzzzzzzzz",
        ],
        index: 3,
      },
      {
        name: "ears",
        options: [
          "azzzazzzzzzz",
          "azzzbzzzzzzz",
          "azzzczzzzzzz",
          "azzzdzzzzzzz",
          "azzzezzzzzzz",
          "azzzfzzzzzzz",
        ],
        index: 4,
      },
      {
        name: "noses",
        options: [
          "azzzzazzzzzz",
          "azzzzbzzzzzz",
          "azzzzczzzzzz",
          "azzzzdzzzzzz",
          "azzzzezzzzzz",
          "azzzzfzzzzzz",
          "azzzzgzzzzzz",
          "azzzzhzzzzzz",
          "azzzzizzzzzz",
          "azzzzjzzzzzz",
          "azzzzkzzzzzz",
          "azzzzlzzzzzz",
          "azzzzmzzzzzz",
          "azzzznzzzzzz",
        ],
        index: 5,
      },
      {
        name: "necks",
        options: [
          "azzzzzazzzzz",
          "azzzzzbzzzzz",
          "azzzzzczzzzz",
          "azzzzzdzzzzz",
          "azzzzzezzzzz",
          "azzzzzfzzzzz",
          "azzzzzgzzzzz",
          "azzzzzhzzzzz",
          "azzzzzizzzzz",
          "azzzzzjzzzzz",
        ],
        index: 6,
      },
      {
        name: "hairs",
        options: [
          "azzzzzzazzzz",
          "azzzzzzbzzzz",
          "azzzzzzczzzz",
          "azzzzzzdzzzz",
          "azzzzzzezzzz",
          "azzzzzzfzzzz",
          "azzzzzzgzzzz",
          "azzzzzzhzzzz",
          "azzzzzzizzzz",
          "azzzzzzjzzzz",
          "azzzzzzkzzzz",
          "azzzzzzlzzzz",
          "azzzzzzmzzzz",
          "azzzzzznzzzz",
          "azzzzzzozzzz",
          "azzzzzzpzzzz",
          "azzzzzzqzzzz",
        ],
        index: 7,
      },
      {
        name: "lines",
        options: ["azzzzzzzazzz"],
        index: 8,
      },
      {
        name: "staches",
        options: ["azzzzzzzzzaz"],
        index: 9,
      },
      {
        name: "props",
        options: [
          "azzzzzzzzzaz",
          "azzzzzzzzzbz",
          "azzzzzzzzzcz",
          "azzzzzzzzzdz",
          "azzzzzzzzzez",
          "azzzzzzzzzfz",
          "azzzzzzzzzgz",
          "azzzzzzzzzhz",
          "azzzzzzzzziz",
          "azzzzzzzzzjz",
          "azzzzzzzzzkz",
          "azzzzzzzzzlz",
          "azzzzzzzzzmz",
          "azzzzzzzzznz",
          "azzzzzzzzzoz",
          "azzzzzzzzzpz",
          "azzzzzzzzzqz",
          "azzzzzzzzzrz",
          "azzzzzzzzzsz",
          "azzzzzzzzztz",
          "azzzzzzzzzuz",
          "azzzzzzzzzvz",
        ],
        index: 10,
      },
      // remove props 2
      {
        name: "props2",
        options: [
          "azzzzzzzzzza",
          "azzzzzzzzzzb",
          "azzzzzzzzzzc",
          "azzzzzzzzzzd",
          "azzzzzzzzzze",
          "azzzzzzzzzzf",
          "azzzzzzzzzzg",
          "azzzzzzzzzzh",
          "azzzzzzzzzzi",
          "azzzzzzzzzzj",
          "azzzzzzzzzzk",
          "azzzzzzzzzzl",
          "azzzzzzzzzzm",
          "azzzzzzzzzzn",
          "azzzzzzzzzzo",
          "azzzzzzzzzzp",
          "azzzzzzzzzzq",
          "azzzzzzzzzzr",
          "azzzzzzzzzzs",
          "azzzzzzzzzzt",
          "azzzzzzzzzzu",
          "azzzzzzzzzzv",
        ],
        index: 11,
      },
    ] as Category[],

    nonBinaryCategoriesHd: [
      {
        name: "shapes",
        options: [
          "azzzzzzzzzzz",
          "bzzzzzzzzzzz",
          "czzzzzzzzzzz",
          "dzzzzzzzzzzz",
          "ezzzzzzzzzzz",
          "fzzzzzzzzzzz",
          "gzzzzzzzzzzz",
        ],
        index: 0,
      },
      {
        name: "eyes",
        options: [
          "aazzzzzzzzzz",
          "abzzzzzzzzzz",
          "aczzzzzzzzzz",
          "adzzzzzzzzzz",
          "aezzzzzzzzzz",
          "afzzzzzzzzzz",
          "agzzzzzzzzzz",
          "ahzzzzzzzzzz",
          "aizzzzzzzzzz",
          "ajzzzzzzzzzz",
          "akzzzzzzzzzz",
          "alzzzzzzzzzz",
          "amzzzzzzzzzz",
          "anzzzzzzzzzz",
          "aozzzzzzzzzz",
          "apzzzzzzzzzz",
          "aqzzzzzzzzzz",
          "arzzzzzzzzzz",
          "aszzzzzzzzzz",
          "atzzzzzzzzzz",
          "auzzzzzzzzzz",
          "avzzzzzzzzzz",
          "awzzzzzzzzzz",
          "axzzzzzzzzzz",
          "ayzzzzzzzzzz",
        ],
        index: 1,
      },
      {
        name: "brows",
        options: [
          "azazzzzzzzzz",
          "azbzzzzzzzzz",
          "azczzzzzzzzz",
          "azdzzzzzzzzz",
          "azezzzzzzzzz",
          "azfzzzzzzzzz",
          "azgzzzzzzzzz",
          "azhzzzzzzzzz",
          "azizzzzzzzzz",
          "azjzzzzzzzzz",
          "azkzzzzzzzzz",
          "azlzzzzzzzzz",
          "azmzzzzzzzzz",
          "aznzzzzzzzzz",
          "azozzzzzzzzz",
          "azpzzzzzzzzz",
          "azqzzzzzzzzz",
          "azrzzzzzzzzz",
        ],
        index: 2,
      },
      {
        name: "mouths",
        options: [
          "azzazzzzzzzz",
          "azzbzzzzzzzz",
          "azzczzzzzzzz",
          "azzdzzzzzzzz",
          "azzezzzzzzzz",
          "azzfzzzzzzzz",
          "azzgzzzzzzzz",
          "azzhzzzzzzzz",
          "azzizzzzzzzz",
          "azzjzzzzzzzz",
          "azzkzzzzzzzz",
          "azzlzzzzzzzz",
          "azzmzzzzzzzz",
          "azznzzzzzzzz",
          "azzozzzzzzzz",
          "azzpzzzzzzzz",
          "azzqzzzzzzzz",
          "azzrzzzzzzzz",
          "azzszzzzzzzz",
        ],
        index: 3,
      },
      {
        name: "ears",
        options: [
          "azzzazzzzzzz",
          "azzzbzzzzzzz",
          "azzzczzzzzzz",
          "azzzdzzzzzzz",
          "azzzezzzzzzz",
          "azzzfzzzzzzz",
          "azzzgzzzzzzz",
          "azzzhzzzzzzz",
          "azzzizzzzzzz",
          "azzzjzzzzzzz",
          "azzzkzzzzzzz",
          "azzzlzzzzzzz",
          "azzzmzzzzzzz",
          "azzznzzzzzzz",
        ],
        index: 4,
      },
      {
        name: "noses",
        options: [
          "azzzzazzzzzz",
          "azzzzbzzzzzz",
          "azzzzczzzzzz",
          "azzzzdzzzzzz",
          "azzzzezzzzzz",
          "azzzzfzzzzzz",
          "azzzzgzzzzzz",
          "azzzzhzzzzzz",
          "azzzzizzzzzz",
          "azzzzjzzzzzz",
          "azzzzkzzzzzz",
          "azzzzlzzzzzz",
          "azzzzmzzzzzz",
          "azzzznzzzzzz",
        ],
        index: 5,
      },
      {
        name: "necks",
        options: [
          "azzzzzazzzzz",
          "azzzzzbzzzzz",
          "azzzzzczzzzz",
          "azzzzzdzzzzz",
          "azzzzzezzzzz",
          "azzzzzfzzzzz",
          "azzzzzgzzzzz",
          "azzzzzhzzzzz",
          "azzzzzizzzzz",
          "azzzzzjzzzzz",
          "azzzzzkzzzzz",
          "azzzzzlzzzzz",
          "azzzzzmzzzzz",
          "azzzzznzzzzz",
          "azzzzzozzzzz",
          "azzzzzpzzzzz",
          "azzzzzqzzzzz",
          "azzzzzrzzzzz",
        ],
        index: 6,
      },
      {
        name: "hairs",
        options: [
          "azzzzzzazzzz",
          "azzzzzzbzzzz",
          "azzzzzzczzzz",
          "azzzzzzdzzzz",
          "azzzzzzezzzz",
          "azzzzzzfzzzz",
          "azzzzzzgzzzz",
          "azzzzzzhzzzz",
          "azzzzzzizzzz",
          "azzzzzzjzzzz",
          "azzzzzzkzzzz",
          "azzzzzzlzzzz",
          "azzzzzzmzzzz",
          "azzzzzznzzzz",
          "azzzzzzozzzz",
          "azzzzzzpzzzz",
          "azzzzzzqzzzz",
          "azzzzzzrzzzz",
          "azzzzzzszzzz",
          "azzzzzztzzzz",
          "azzzzzzuzzzz",
          "azzzzzzvzzzz",
          "azzzzzzwzzzz",
          "azzzzzzxzzzz",
          "azzzzzzyzzzz",
          "azzzzzzAzzzz",
          "azzzzzzBzzzz",
          "azzzzzzCzzzz",
          "azzzzzzDzzzz",
          "azzzzzzEzzzz",
          "azzzzzzFzzzz",
          "azzzzzzGzzzz",
        ],
        index: 7,
      },
      {
        name: "staches",
        options: [
          "azzzzzzzazzz",
          "azzzzzzzbzzz",
          "azzzzzzzczzz",
          "azzzzzzzdzzz",
          "azzzzzzzezzz",
          "azzzzzzzfzzz",
          "azzzzzzzgzzz",
          "azzzzzzzhzzz",
          "azzzzzzzizzz",
          "azzzzzzzjzzz",
          "azzzzzzzkzzz",
          "azzzzzzzlzzz",
          "azzzzzzzmzzz",
          "azzzzzzznzzz",
          "azzzzzzzozzz",
          "azzzzzzzpzzz",
          "azzzzzzzqzzz",
          "azzzzzzzrzzz",
        ],
        index: 8,
      },
      {
        name: "lines",
        options: [
          "azzzzzzzzazz",
          "azzzzzzzzbzz",
          "azzzzzzzzczz",
          "azzzzzzzzdzz",
          "azzzzzzzzezz",
          "azzzzzzzzfzz",
          "azzzzzzzzgzz",
          "azzzzzzzzhzz",
        ],
        index: 9,
      },
      {
        name: "props",
        options: [
          "azzzzzzzzzaz",
          "azzzzzzzzzbz",
          "azzzzzzzzzcz",
          "azzzzzzzzzdz",
          "azzzzzzzzzez",
          "azzzzzzzzzfz",
          "azzzzzzzzzgz",
          "azzzzzzzzzhz",
          "azzzzzzzzziz",
          "azzzzzzzzzjz",
          "azzzzzzzzzkz",
          "azzzzzzzzzlz",
          "azzzzzzzzzmz",
          "azzzzzzzzznz",
          "azzzzzzzzzoz",
          "azzzzzzzzzpz",
          "azzzzzzzzzqz",
          "azzzzzzzzzrz",
          "azzzzzzzzzsz",
        ],
        index: 10,
      },
      {
        name: "props2",
        options: [
          "azzzzzzzzzza",
          "azzzzzzzzzzb",
          "azzzzzzzzzzc",
          "azzzzzzzzzzd",
          "azzzzzzzzzze",
          "azzzzzzzzzzf",
          "azzzzzzzzzzg",
          "azzzzzzzzzzh",
          "azzzzzzzzzzi",
          "azzzzzzzzzzj",
          "azzzzzzzzzzk",
          "azzzzzzzzzzl",
          "azzzzzzzzzzm",
          "azzzzzzzzzzn",
          "azzzzzzzzzzo",
          "azzzzzzzzzzp",
          "azzzzzzzzzzq",
          "azzzzzzzzzzr",
          "azzzzzzzzzzs",
        ],
        index: 11,
      },
    ] as Category[],
  },
  mutations: {
    TOGGLE_DARK_MODE(state): void {
      state.isDarkMode = !state.isDarkMode;
    },
    SET_USER_AVATAR(state, sequence: string): void {
      state.userAvatar = sequence;
    },
  },
});

// define your own `useStore` composition function
export function useStore() {
  return baseUseStore(key);
}
